# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PranshuParmar.witr
PackageVersion: 0.3.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: witr.exe
  PortableCommandAlias: witr
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/pranshuparmar/witr/releases/download/v0.3.4/witr-windows-amd64.zip
  InstallerSha256: 34EF930E6F53C026E952F5952442281640BAE551E59477137A045F9A2141188F
- Architecture: arm64
  InstallerUrl: https://github.com/pranshuparmar/witr/releases/download/v0.3.4/witr-windows-arm64.zip
  InstallerSha256: C1DB651220BC8A86433FBA7E680C87F9DB868A41C0FB144427F37750EC62A7CE
ManifestType: installer
ManifestVersion: 1.12.0
