name: Winget Auto Update

on:
  workflow_dispatch:

jobs:
  winget:
    runs-on: windows-latest

    steps:
      - name: Checkout packaging repo
        uses: actions/checkout@v6

      - name: Install wingetcreate
        shell: powershell
        run: |
          $url = "https://github.com/microsoft/winget-create/releases/latest/download/wingetcreate.exe"
          $dest = "$env:USERPROFILE\wingetcreate.exe"
          Invoke-WebRequest -Uri $url -OutFile $dest
          echo "$env:USERPROFILE" >> $env:GITHUB_PATH

      - name: Fetch latest witr release
        id: release
        shell: powershell
        run: |
          $repo = "pranshuparmar/witr"
          $url = "https://api.github.com/repos/$repo/releases/latest"
          $resp = Invoke-RestMethod $url
          $tag = $resp.tag_name
          $version = $tag.TrimStart("v")
          "version=$version" >> $env:GITHUB_OUTPUT

      - name: Generate winget manifests
        shell: powershell
        run: |
          $version = "${{ steps.release.outputs.version }}"
          mkdir temp_manifests
          
          wingetcreate update PranshuParmar.witr `
            --version $version `
            --urls https://github.com/pranshuparmar/witr/releases/download/v$version/witr-windows-amd64.zip https://github.com/pranshuparmar/witr/releases/download/v$version/witr-windows-arm64.zip `
            --out temp_manifests

      - name: Submit manifests to winget-pkgs
        env:
          WINGET_TOKEN: ${{ secrets.WINGET_PAT }}
        shell: powershell
        run: |
          $version = "${{ steps.release.outputs.version }}"
          wingetcreate submit `
            temp_manifests `
            --prtitle "witr $version" `
            --token $env:WINGET_TOKEN

      
      - name: Commit and Push
        shell: powershell
        run: |
          $version = "${{ steps.release.outputs.version }}"
          $repo_path = "winget/manifests/p/PranshuParmar/witr/$version"
          New-Item -ItemType Directory -Force -Path $repo_path
          Copy-Item "temp_manifests/*" -Destination $repo_path -Recurse

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if (git status --porcelain) {
            git add .
            git commit -m "chore: update winget manifests [skip ci]"
            git push origin main
          } else {
            Write-Host "No changes to commit."
          }
